version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: gnosispay-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: nestdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U testuser -d nestdb']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
